main/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin


urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^centrifugal_pump/result/$','wyswietl.views.centrifugal_pump_result'),
    url(r'^centrifugal_pump/form/$','wyswietl.views.centrifugal_pump_form'),
    url(r'^$','wyswietl.views.index'),
    url(r'^boiler/forms/$','wyswietl.views.boiler_forms'),
    url(r'^boiler/result/$','wyswietl.views.boiler_result'),
    url(r'^electrostatic_precipitators/form/$','wyswietl.views.electrostatic_form'),
    url(r'^electrostatic_precipitators/result/$','wyswietl.views.electrostatic_result'),
    url(r'^scr_reactor_nox/form/$', 'wyswietl.views.scr_form'),
    url(r'^scr_reactor_nox/result/$', 'wyswietl.views.scr_result')
)

wyswietl/models.py
from django.db import models

class Odbiorca(models.Model):
     imie=models.CharField(max_length=20)
     nazwisko=models.CharField(max_length=20)
     
     def __str__(self):
         return self.nazwisko


class Parametry(models.Model):    
     wysokosc=models.IntegerField()
     obroty=models.IntegerField()
     strumien=models.IntegerField()

     def __str__(self):
         return self.wysokosc


class UOAP0(models.Model):
     wegiel_kamienny="Wegiel kamienny"
     wegiel_brunatny="Wegiel brunatny"
     rodzaje_paliwa=((wegiel_kamienny,'Wegiel kamienny'),(wegiel_brunatny,'Wegiel brunatny'))
     rodzaj_spalanego_paliwa=models.CharField(max_length=20,choices=rodzaje_paliwa)
     wydajnosc_kotla=models.IntegerField()
     masowy_udzial_wegla=models.IntegerField()
     masowy_udzial_wodoru=models.IntegerField() 
     masowy_udzial_tlenu=models.IntegerField()
     masowy_udzial_azotu=models.IntegerField()
     masowy_udzial_siarki=models.IntegerField()
     zawartosc_popiolu_w_paliwie_w_stanie_roboczym=models.FloatField()
     zawartosc_wilgoci_w_paliwie_w_stanie_roboczym=models.FloatField()
     wspolczynnik_nadmiaru_powietrza_w_komorze_paleniskowej=models.FloatField()
     udzial_popiolu_unoszonego_przez_spaliny_do_kanalow_kotla=models.FloatField()
     srednia_zawartosc_wilgoci=models.FloatField()
     gestosc_CO2_w_WU=models.FloatField()
     gestosc_SO2_w_WU=models.FloatField()
     gestosc_N2_w_WU=models.FloatField()
     gestosc_pary_wodnej_w_WU=models.FloatField()
     gestosc_powietrza_w_WU=models.FloatField()
     przyrost_wspolczynnika_nadmiaru_powietrza_na_drodze_komora_paleniskowa_a_kanal_spalin=models.FloatField()
     cisnienie_wody_zasilajacej=models.IntegerField()
     temperatura_wody_zasilajacej=models.IntegerField()
     cisnienie_pary=models.FloatField()
     temperatura_pary=models.FloatField()
     sprawnosc_kotla=models.FloatField()
     strata_niezupelnego_spalania=models.IntegerField()
     podcisnienie_spalin_w_kanale=models.FloatField()
     temperatura_spalin_w_kanale=models.IntegerField()
     referencyjna_zawartosc_tlenu_w_spalinach_suchych=models.IntegerField()
     cisnienie_umowne=models.IntegerField()
     temperatura_umowna=models.IntegerField()


class UOAP2(models.Model):
     predkosci=((15,'15'),(16,'16'),(17,'17'),(18,'18'),(19,'19'),(20,'20'))
     predkosc_spalin_w_kanale=models.CharField(max_length=6,choices=predkosci)
     dlugosci=((3,'3'),(4,'4'),(5,'5'))
     dlugosc_pola_elektrycznego_elektrofiltru=models.CharField(max_length=3,choices=dlugosci)
     wysokosc_pola_elektrycznego_elektrofiltru=models.FloatField()
     predkosc_spalin_w_komorze_elektrofiltru=models.FloatField()
     kat=enumerate((30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90))    
     kat_rozwarcia_konfuzora=models.CharField(max_length=62,choices=kat)
     kat2=enumerate((45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60))
     kat_pochylenia_sciany_leja_do_poziomu=models.CharField(max_length=26,choices=kat2)
     kat3=enumerate((90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120))
     kat_rozwarcia_konfuzora=models.CharField(max_length=31,choices=kat3)
     wymiar=enumerate((200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,361,362,363,364,365,366,367,368,369,370,371,372,373,374,375,376,377,378,379,380,381,382,383,384,385,386,387,388,389,390,391,392,393,394,395,396,397,398,399,400,401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,416,417,418,419,420,421,422,423,424,425,426,427,428,429,430,431,432,433,434,435,436,437,438,439,440,441,442,443,444,445,446,447,448,449,450,451,452,453,454,455,456,457,458,459,460,461,462,463,464,465,466,467,468,469,470,471,472,473,474,475,476,477,478,479,480,481,482,483,484,485,486,487,488,489,490,491,492,493,494,495,496,497,498,499,500))
     wymiary_bokow_otworu_wylotowego_leja_o_ksztalcie_prostokatnym=models.CharField(max_length=300, choices=wymiar)
     predkosc_wedrowania_w_dla_elektrofiltru_typu_plyta_drut=models.FloatField()

wyswietl/forms.py
from django import forms
from .models import Odbiorca
from .models import Parametry
from .models import UOAP0
from .models import UOAP2

class OdbiorcaForm(forms.ModelForm):
   
    class Meta:
        model=Odbiorca
        field='__all__'
        exclude = ()


class ParametryForm(forms.ModelForm):
       
     class Meta:
       model=Parametry
       field='__all__'
       exclude = ()


class UOAP0Form(forms.ModelForm):
     
     class Meta:
         model=UOAP0
         field='__all__'
         exclude = ()


class UOAP2Form(forms.ModelForm):
     
    class Meta:
        model=UOAP2                    
        exclude = ()

wyswietl/views.py
from django.shortcuts import redirect
from django.shortcuts import render
from django.http import HttpResponse
from django.shortcuts import render_to_response
from .forms import OdbiorcaForm
from .forms import ParametryForm
from .models import Odbiorca
from .models import Parametry
from .forms import UOAP0Form
from .models import UOAP0
from .models import UOAP2
from .forms import UOAP2Form


def index(request):
    return render_to_response('base/index.html')


def centrifugal_pump_form(request):
    """
        Template to P3 Project
    """
    if request.method == "POST":
       form=ParametryForm(request.POST)
       if form.is_valid():
            form.save()
            return redirect(centrifugal_pump_result) 
    else:
        form=ParametryForm()
    return render(request,'p3/centrifugal_pump_form.html', {'form':form})


def centrifugal_pump_result(request):
    """
        Result of P3 Project
    """
    post=Odbiorca.objects.all().last()
    parametry=Parametry.objects.all().last()
    return render(request,'p3/centrifugal_pump_result.html',{'parametry':parametry})


def electrostatic_form(request):
    """
        Form of P2 project
    """
    if request.method == "POST":
       form=UOAP2Form(request.POST)
       if form.is_valid():
            form.save()
            return redirect(electrostatic_result)
    else:
        form=UOAP2Form()
    return render(request,'p2/electrostatic_form.html',{'form':form})


def electrostatic_result(request):
    """
        Result of P3 project
    """
    post = Odbiorca.objects.all().last()
    parametry = UOAP2.objects.all().last()
    return uoapp0(request,'p2/electrostatic_result.html',{'uoap2':parametry})


def boiler_forms(request):
    if request.method == "POST":
       form=UOAP0Form(request.POST)
       if form.is_valid():
            form.save()
            return redirect(boiler_result)
    else:
        form=UOAP0Form()
    return render(request,'p0/boiler_forms.html',{'form':form})


def boiler_result(request):
     post=Odbiorca.objects.all().last()
     parametry=UOAP0.objects.all().last()
     return render(request,'test.html',{'uoap0':parametry})


def scr_form(request):
    """
        This is a form view to generate SCR Reactor Project
    """
    return render(request,'p4/scr_reactor_form.html')

def scr_result(request):
    """
        This is a form view to generate SCR Reactor Project
    """
    return render(request,'p4/scr_reactor_result.html')

wyswietl/templates/UOAP0.html
{% extends "base.html" %}
{% block content %}
    <center>
      <h1>Parametry wejsciowe do projektu P00:</h1>
      <form method="POST" class="post-form">{% csrf_token %}
                             {{ form.as_p }}
         <button type="submit" class="save btn btn-default">Dodaj</button>
       </form>
     </center>
{% endblock %}
~                                                                                                                                                
~                

wyswietl/templates/edit.html
<html>
	<head>
		<title>Pomp edit</title>
	</head>
	<body> 
                <center>
                        <h2>Edit of the pump parametrs:: </h2>
                        <form method="POST" class="post-form">
                                {% csrf_token %}
                                {{ form2.as_p }}
                                <button type="submit" class="save btn btn-default">Dodaj</button>
                        </form>
                </center>
	</body>
</html>

wyswietl/templates/p0/boiler_forms.html
{% extends "base/base.html" %}
{% block content %}

<style>
	#id_wydajnosc_kotla{background-color: white;}
	#id_masowy_udzial_tlenu{background-color: white;}
	#id_masowy_udzial_wegla{background-color: white;}
	#id_masowy_udzial_wodoru{background-color: white;}
	#id_masowy_udzial_azotu{background-color: white;}
	#id_masowy_udzial_siarki{background-color: white;}
	#id_zawartosc_popiolu_w_paliwie_w_stanie_roboczym{background-color: white;}
	#id_zawartosc_wilgoci_w_paliwie_w_stanie_roboczym{background-color: white;}
    #id_wspolczynnik_nadmiaru_powietrza_w_komorze_paleniskowej{background-color: white;}
    #id_udzial_popiolu_unoszonego_przez_spaliny_do_kanalow_kotla{background-color: white;}
    #id_srednia_zawartosc_wilgoci{background-color: white;}
    #id_gestosc_CO2_w_WU{background-color: white;}
	#id_gestosc_SO2_w_WU{background-color: white;}
	#id_gestosc_N2_w_WU{background-color: white;}
	#id_gestosc_pary_wodnej_w_WU{background-color: white;}
	#id_gestosc_powietrza_w_WU{background-color: white;}
	#id_przyrost_wspolczynnika_nadmiaru_powietrza_na_drodze_komora_paleniskowa_a_kanal_spalin{background-color: white;}
	#id_cisnienie_wody_zasilajacej{background-color: white;}
	#id_temperatura_wody_zasilajacej{background-color: white;}
	#id_cisnienie_pary{background-color: white;}
	#id_temperatura_pary{background-color: white;}
	#id_sprawnosc_kotla{background-color: white;}
	#id_strata_niezupelnego_spalania{background-color: white;}
	#id_podcisnienie_spalin_w_kanale{background-color: white;}
	#id_temperatura_spalin_w_kanale{background-color: white;}
	#id_referencyjna_zawartosc_tlenu_w_spalinach_suchych{background-color: white;}
    #id_cisnienie_umowne{background-color: white;}
    #id_temperatura_umowna{background-color: white;}
	form{border-style: solid 1px; text-align: justify;}
	button{background-color:silver;border-style: solid 2px;color: #444444;height: 30px; width: 200px;font-size: 15px; text-align: center;}
	h1{text-align: center;}
</style>


<center>
	<h1 style="color: black; text-decoration: underline;">Parametry wejsciowe dla projektu P0</h1>
	<form style="color: black;" method="POST" class="post-form">
		{% csrf_token %}
		{{ form.as_p }}
		<button type="submit" class="save btn btn-default">Generuj obliczenia</button>
	</form>
</center>
{% endblock %}
~

wyswietl/templates/p2/electrostatic_form.html
{% extends "base/base.html"%}
{% block content %}
      <center>
      <h1 style="color: black; text-decoration: underline;">Parametry wejsciowe dla projektu P2</h1>
      <form style="color: black;" 
                         method="POST" class="post-form">{% csrf_token %}
                             {{ form.as_p }}
         <button type="submit" class="save btn btn-default">Generuj obliczenia</button>
       </form>
     </center>


{% endblock %}

wyswietl/templates/p2/electrostatic_result.html
{% extends "base/base.html" %}
{% block content %}

	<center>
		<table>
			<tr>
				<td></td>
				<td></td>
			</tr>
		</table>
	</center>

{% endblock %}

wyswietl/templates/p3/centrifugal_pump_form.html
 {% extends "base/base.html" %}
{% block content %}
    <center>
      <h1>Parametry pompy odsrodkowej:</h1>
      <form method="POST" class="post-form">{% csrf_token %}
                             {{ form.as_p }}
         <button type="submit" class="save btn btn-default">Dodaj</button>
       </form>
     </center>
{% endblock %}

wyswietl/templates/p3/centrifugal_pump_result.html
{% extends "base/base.html" %}
{% block content %}


<style>
	td {
		color: black;
	}

	table {
		width: 800px;

	}

	a {
		text-align: center;
		text-color: black;
	}

	#header {
		text-align: center;
		color: black;
		font-size: 25px;
		text-shadow: 5px 5px 5px LightGray;
		padding: 1%;
	}

	#header-row {
		background: LightGray;
		font-size: 20px;
		text-align: center;
		border-radius: 25px;
	}

	#body-row {
		font-size: 15px;
		border-radius: 25px;
		background: lightgreen;
		text-align: center;
	}
</style>

<h1 id="header">Basic parametrs:</h1>
<hr>
<div class="container">
	<div id="header-row" class="row">
		<div class="col-sm-4">
			<p>Wydajnosc pompy:</p>
			<p>Q[\(m^3 \over h \)]</p>
		</div>
		<div class="col-sm-4">
			<p>Wysokosc podnoszenia:</p>
			<p>H[\( m \)]</p>
		</div>
		<div class="col-sm-4">
			<p>Predkosc obrotowa:</p>
			<p>n[\( RPM \)]</p>
		</div>
	</div>

	<br>
	<div id="body-row" class="row">
		<div class="col-sm-4">
			<p>{{parametry.strumien}}</p>
		</div>
		<div class="col-sm-4">
			<p>{{parametry.wysokosc}}</p>
		</div>
		<div class="col-sm-4">
			<p>{{parametry.obroty}}</p>
		</div>
	</div>
</div>


<h1 id="header">Obliczenia charakterystyki ukladu:</h1>
<hr>
<div class="container">
	<div id="header-row" class="row">
		<div class="col-sm-6">
			<p>Wyznaczamy wyroznik oporu ukladu:</p>
		</div>
		<div class="col-sm-6">
			<p>Wyznaczenie charakterystyki ukladu:</p>
		</div>
	</div>
	<br>
	<div id="body-row" class="row">
		<div class="col-sm-6">
			<p>...</p>
		</div>
		<div class="col-sm-6">
			<p>...</p>
		</div>
	</div>
</div>


{% endblock %}

wyswietl/templates/p4/scr_reactor_form.html
{% extends 'base/base.html' %}
{% block content %}

    <style>
        label {
            padding: 3%;
        }

        h1 {
            text-align: center;
        }

        p {
            font-size: 17px;
            text: Times;
            padding: 1%;
            margin-left: 20%;
            margin-right: 20%;
        }

    </style>


    <h1>SCR Reactor form to reduce NOX</h1>
    <hr>
    <p>
        This is a single form to generate results of calculations. When we add input
        variables we receive full callculations to ours project. We don't need to have
        some dates from scientific boards. This program prepare all needed dates to you. 
    </p>


    <form class="form-horizontal" action="/scr_reactor_nox/result/">

        <div class="container">

            <div class="row">
                <label class="control-label col-sm-3" for="email">Tu:</label>
                <div class="col-sm-6">
                    <input type="text" class="form-control" id="email" name="email" required>
                </div>
            </div>

            <div class="row">
                <label class="control-label col-sm-3" for="pwd">t1:</label>
                <div class="col-sm-6">          
                    <input type="text" class="form-control" id="pwd" name="pwd" required>
                </div>
            </div>

            <div class="row">
                <label class="control-label col-sm-3" for="pwd">tk:</label>
                <div class="col-sm-6">          
                    <input type="text" class="form-control" id="pwd" name="pwd" required>
                </div>
            </div>

            <div class="row">
                <label class="control-label col-sm-3" for="pwd">t1:</label>
                <div class="col-sm-6">          
                    <input type="text" class="form-control" id="pwd" name="pwd" required>
                </div>
            </div>

            <div class="row">
                <label class="control-label col-sm-3" for="pwd">Ve:</label>
                <div class="col-sm-6">          
                    <input type="text" class="form-control" id="pwd" name="pwd" required>
                </div>
            </div>

            <div class="row">
                <div class="col-sm-offset-5 col-sm-3">
                    <button type="submit" class="btn btn-default">Generate</button>
                </div>
            </div>

        </div>
  </form>
{% endblock %}

wyswietl/templates/p4/scr_reactor_result.html
{% extends 'base/base.html' %}
{% block content %}

    <style>
        label {
            padding: 3%;
        }

        h1 {
            text-align: center;
        }

        p {
            font-size: 17px;
            text: Times;
            padding: 1%;
            margin-left: 10%;
            margin-right: 10%;
        }


    </style>

    <h1>SCR Reactor result to reduce NOX</h1>
    <hr>
    <p>
        Tabel bellow present all calculation results. They present 
        they present not only calculated data but also the most
        optimal data from scientific boards.
    </p>
    <div class="container">
        <table class="table table-striped">
            <thead>
            <tr>
                <th>Parameter name</th>
                <th>Parameter value</th>
                <th>Units</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>Flue volume flow</td>
                <td>123</td>
                <td>-</td>
            </tr>
            <tr>
                <td>Flue gas volume flow in the reactor</td>
                <td>321</td>
                <td>-</td>
            </tr>
            <tr>
                <td>The area of the total cross-section of a single cell</td>
                <td>123,32</td>
                <td>-</td>
            </tr>
            <tr>
                <td>The area of the total cross-section of a single cell</td>
                <td>123,32</td>
                <td>-</td>
            </tr>
            <tr>
                <td>The area of the total cross-section of a single cell</td>
                <td>123,32</td>
                <td>-</td>
            </tr>
            <tr>
                <td>The area of the total cross-section of a single cell</td>
                <td>123,32</td>
                <td>-</td>
            </tr>
            <tr>
                <td>The area of the total cross-section of a single cell</td>
                <td>123,32</td>
                <td>-</td>
            </tr>
            <tr>
                <td>The area of the total cross-section of a single cell</td>
                <td>123,32</td>
                <td>-</td>
            </tr>
            </tbody>
        </table>
    </div>




{% endblock %}

wyswietl/templates/test.html
{% extends "base.html" %}
{% block content %}


<style>
	td {
		color: black;
	}

	table {
		width: 800px;

	}

	a {
		text-align: center;
		text-color: black;
	}

	#header {
		text-align: center;
		color: black;
		font-size: 25px;
		text-shadow: 5px 5px 5px LightGray;
		padding: 1%;
	}

	#header-row {
		background: LightGray;
		font-size: 20px;
		text-align: center;
		border-radius: 25px;
	}

	#body-row {
		font-size: 15px;
		border-radius: 25px;
		background: lightgreen;
		text-align: center;
	}
</style>

<h1 id="header">Basic parametrs:</h1>
<hr>
<div class="container">
	<div id="header-row" class="row">
		<div class="col-sm-4">
			<p>Wydajnosc pompy:</p>
			<p>Q[\(m^3 \over h \)]</p>
		</div>
		<div class="col-sm-4">
			<p>Wysokosc podnoszenia:</p>
			<p>H[\( m \)]</p>
		</div>
		<div class="col-sm-4">
			<p>Predkosc obrotowa:</p>
			<p>n[\( RPM \)]</p>
		</div>
	</div>

	<br>
	<div id="body-row" class="row">
		<div class="col-sm-4">
			<p>{{parametry.strumien}}</p>
		</div>
		<div class="col-sm-4">
			<p>{{parametry.wysokosc}}</p>
		</div>
		<div class="col-sm-4">
			<p>{{parametry.obroty}}</p>
		</div>
	</div>
</div>


<h1 id="header">Obliczenia charakterystyki ukladu:</h1>
<hr>
<div class="container">
	<div id="header-row" class="row">
		<div class="col-sm-6">
			<p>Wyznaczamy wyroznik oporu ukladu:</p>
		</div>
		<div class="col-sm-6">
			<p>Wyznaczenie charakterystyki ukladu:</p>
		</div>
	</div>
	<br>
	<div id="body-row" class="row">
		<div class="col-sm-6">
			<p>...</p>
		</div>
		<div class="col-sm-6">
			<p>...</p>
		</div>
	</div>
</div>


{% endblock %}

wyswietl/templates/uoap2result.html
{% extends "base.html" %}
{% block content %}

	<center>
		<table>
			<tr>
				<td></td>
				<td></td>
			</tr>
		</table>
	</center>

{% endblock %}

wyswietl/templates/uoapp0.html
{% extends "base.html" %}
{% block content %}

<style>
	#id_wydajnosc_kotla{background-color: white;}
	#id_masowy_udzial_tlenu{background-color: white;}
	#id_masowy_udzial_wegla{background-color: white;}
	#id_masowy_udzial_wodoru{background-color: white;}
	#id_masowy_udzial_azotu{background-color: white;}
	#id_masowy_udzial_siarki{background-color: white;}
	#id_zawartosc_popiolu_w_paliwie_w_stanie_roboczym{background-color: white;}
	#id_zawartosc_wilgoci_w_paliwie_w_stanie_roboczym{background-color: white;}
    #id_wspolczynnik_nadmiaru_powietrza_w_komorze_paleniskowej{background-color: white;}
    #id_udzial_popiolu_unoszonego_przez_spaliny_do_kanalow_kotla{background-color: white;}
    #id_srednia_zawartosc_wilgoci{background-color: white;}
    #id_gestosc_CO2_w_WU{background-color: white;}
	#id_gestosc_SO2_w_WU{background-color: white;}
	#id_gestosc_N2_w_WU{background-color: white;}
	#id_gestosc_pary_wodnej_w_WU{background-color: white;}
	#id_gestosc_powietrza_w_WU{background-color: white;}
	#id_przyrost_wspolczynnika_nadmiaru_powietrza_na_drodze_komora_paleniskowa_a_kanal_spalin{background-color: white;}
	#id_cisnienie_wody_zasilajacej{background-color: white;}
	#id_temperatura_wody_zasilajacej{background-color: white;}
	#id_cisnienie_pary{background-color: white;}
	#id_temperatura_pary{background-color: white;}
	#id_sprawnosc_kotla{background-color: white;}
	#id_strata_niezupelnego_spalania{background-color: white;}
	#id_podcisnienie_spalin_w_kanale{background-color: white;}
	#id_temperatura_spalin_w_kanale{background-color: white;}
	#id_referencyjna_zawartosc_tlenu_w_spalinach_suchych{background-color: white;}
    #id_cisnienie_umowne{background-color: white;}
    #id_temperatura_umowna{background-color: white;}
	form{border-style: solid 1px; text-align: justify;}
	button{background-color:silver;border-style: solid 2px;color: #444444;height: 30px; width: 200px;font-size: 15px; text-align: center;}
	h1{text-align: center;}
</style>


<center>
	<h1 style="color: black; text-decoration: underline;">Parametry wejsciowe dla projektu P0</h1>
	<form style="color: black;" method="POST" class="post-form">
		{% csrf_token %}
		{{ form.as_p }}
		<button type="submit" class="save btn btn-default">Generuj obliczenia</button>
	</form>
</center>
{% endblock %}
~

wyswietl/templates/uoapp2.html
{% extends "base.html"%}
{% block content %}
      <center>
      <h1 style="color: black; text-decoration: underline;">Parametry wejsciowe dla projektu P2</h1>
      <form style="color: black;" 
                         method="POST" class="post-form">{% csrf_token %}
                             {{ form.as_p }}
         <button type="submit" class="save btn btn-default">Generuj obliczenia</button>
       </form>
     </center>


{% endblock %}

wyswietl/templates/uoaprojects.html
{% extends "base.html" %}
{% block content %}
    <style>
	td
	{
		color: black;
	}
	table
	{	
		width:800px;
		
	}
	a
	{
		text-align: center;
		text-color: black;
	}

	#h1{
		text-align: center;
		color: black;
		font-size: 35px;
		text-shadow: 4px 4px 5px black}
    </style>

	<div class="panel-group" id="accordion">
			<div class="faqHeader">
				<h1 id = "h1">Projects</h1><hr><br>
			</div>
			<div class="panel panel-default">

				<div class="panel-heading">
					<h4 class="panel-title">
						<a class="accordion-toggle" data-toggle="collapse"
						data-parent="#accordion" href="#collapseOne">P0 Protection Atmospere Devices</a>
					</h4>
				</div>
				<div id="collapseOne" class="panel-collapse collapse in">
					<div class="panel-body">
						<p>
							This project was created to prepared to
							finish my P0 project on the university. (Boiler)
						</p>
						<a href="/p0/odbiorca/">link</a> 
					</div>
				</div>
			</div>
			<div class="panel panel-default">
				<div class="panel-heading">
					<h4 class="panel-title">
						<a class="accordion-toggle collapsed" data-toggle="collapse"
						data-parent="#accordion" href="#collapseTen">P2 Protection Atmospere Devices</a>
					</h4>
				</div>
				<div id="collapseTen" class="panel-collapse collapse">
					<div class="panel-body">
						<a href="/p2/odbiorca/">link</a> 
					</div>
				</div>
			</div>
		</div>

{% endblock %}